CREATE TABLE IF NOT EXISTS category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS recipe (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL ,
  description TEXT NOT NULL ,
  categoryId int NOT NULL ,
  FOREIGN KEY (categoryId)
  REFERENCES category (id)
    ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
